<a href="https://colab.research.google.com/github/koba4real/machine-learning-lab/blob/main/03_numpy_exercises.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Numpy Practice - Hints - Unibs 2021

#### Import the numpy package under the name `np` and print version and configuration (base)
`hint: import … as, np.__version__, np.show_config`

In [4]:
import numpy as np
print(np.__version__)
np.show_config()

2.0.2
Build Dependencies:
  blas:
    detection method: pkgconfig
    found: true
    include directory: /opt/_internal/cpython-3.11.8/lib/python3.11/site-packages/scipy_openblas64/include
    lib directory: /opt/_internal/cpython-3.11.8/lib/python3.11/site-packages/scipy_openblas64/lib
    name: scipy-openblas
    openblas configuration: OpenBLAS 0.3.27  USE64BITINT DYNAMIC_ARCH NO_AFFINITY
      Zen MAX_THREADS=64
    pc file directory: /project/.openblas
    version: 0.3.27
  lapack:
    detection method: pkgconfig
    found: true
    include directory: /opt/_internal/cpython-3.11.8/lib/python3.11/site-packages/scipy_openblas64/include
    lib directory: /opt/_internal/cpython-3.11.8/lib/python3.11/site-packages/scipy_openblas64/lib
    name: scipy-openblas
    openblas configuration: OpenBLAS 0.3.27  USE64BITINT DYNAMIC_ARCH NO_AFFINITY
      Zen MAX_THREADS=64
    pc file directory: /project/.openblas
    version: 0.3.27
Compilers:
  c:
    commands: cc
    linker: ld.bfd
    name

## Base Practice

#### 1. Create a null vector of size 10 but the fifth value which is 1 (base)
`hint: array[4]`

In [5]:
array = np.zeros(10)
array[4] = 1
print(array)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### 2. Create a 3x3 matrix with values ranging from 0 to 8 with zeros on the diagonal (base)
`hint: np.arange, reshape, np.eye`

In [14]:
matrix = np.arange(9).reshape(3, 3)
anti=np.eye(3)
matrix=matrix-anti*matrix
print(matrix)

[[0. 1. 2.]
 [3. 0. 5.]
 [6. 7. 0.]]


#### 3. How to add a border (filled with 0's) around an 5x5 matrix of ones? (base)
`hint: np.ones, np.pad`

In [16]:
np.pad(np.ones((5,5)), pad_width=1, mode='constant', constant_values=0)

array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0.]])

#### 4. Normalize a 5x5 random matrix (base)
`hint: (x - mean) / std, np.mean, np.std`

In [17]:
np.random.seed(0)
x=np.random.rand(5,5)
mean=np.mean(x)
std=np.std(x)
print((x-mean)/std)

[[-0.14854421  0.44055117  0.04247881 -0.1624605  -0.59169993]
 [ 0.19519398 -0.54236874  1.06578972  1.32033341 -0.73408512]
 [ 0.71154487 -0.21907095 -0.08045184  1.18555078 -1.84023484]
 [-1.78325269 -2.02016749  0.85634317  0.66350295  0.98873998]
 [ 1.37328739  0.73786513 -0.4577726   0.67190312 -1.67297558]]


#### 5. Multiply a 5x3 matrix of ones by a 3x2 matrix of ones (real matrix product) (base)
`hint: np.dot`

In [19]:
np.dot(np.ones((5,3)),np.ones((3,2)))

array([[3., 3.],
       [3., 3.],
       [3., 3.],
       [3., 3.],
       [3., 3.]])

## Intermediate Practice

#### 6. Create a vector of size 10 with values ranging from 0 to 1, both excluded (intermediate)
`hint: np.linspace`

In [22]:
np.linspace(0,1,12)[1:-1]

array([0.09090909, 0.18181818, 0.27272727, 0.36363636, 0.45454545,
       0.54545455, 0.63636364, 0.72727273, 0.81818182, 0.90909091])

#### 7. Create a random vector of size 10 with values in range (-3, 12) and sort it (intermediate)
`hint: sort`

In [23]:
sort=np.sort(np.random.randint(-3,12,10))
print(sort)

[-3 -3 -2  0  1  4  6  6  7 11]


#### 8. Create random vector of size 10 and replace the maximum value by its additive inverse and the minimum value (of the original array) with the median value (intermediate)
`hint: argmax, argmin`

In [27]:

vettore = np.random.randint(-100, 100, size=10)
print("Vettore originale:", vettore)

vettore[np.argmax(vettore)] = -vettore[np.argmax(vettore)]
vettore[np.argmin(vettore)] = int(np.median(vettore))

print("Vettore modificato:", vettore)

Vettore originale: [-83 -21  32   5 -58  86 -69  20 -99 -35]
Vettore modificato: [-83 -21  32   5 -58 -86 -69  20 -46 -35]


#### 9. Randomly replace p elements in a 2D nxn zero matrix to 1 (intermediate)
`hint: np.put, np.random.choice`

In [31]:
np.put(np.zeros((10,10)), np.random.choice(range(100), 10, replace=False), 1)

#### 10. Subtract the mean of each row of a random 5x10 matrix (intermediate)
`hint: mean(axis=,keepdims=)`

In [33]:
matrice = np.random.randn(5, 10)
print("Matrice originale:\n", matrice)

media_righe = matrice.mean(axis=1, keepdims=True)

matrice_modificata = matrice - media_righe

print("\nMatrice dopo la sottrazione della media di ogni riga:\n", matrice_modificata)

Matrice originale:
 [[-0.86249519  1.08245595 -0.14978222 -1.01479235  0.68895269 -2.34110832
   0.12614029  1.20093909  0.96299691  1.59006635]
 [ 0.61723123 -0.47781636  1.73627939  2.97069986  0.61513455  2.0669435
   0.07754323 -0.45231908 -0.59755485  1.308767  ]
 [ 0.38587713 -0.00719074 -0.66298574 -1.34704629 -0.09519928 -0.22772779
   0.43243668  0.46693969 -1.3402814   1.42285966]
 [ 0.99379727 -0.61651086  0.20493776 -0.47954552  1.51238621 -1.34683907
  -2.78073771 -0.0894738   0.55814156  0.75572522]
 [ 0.47821507 -0.05390584 -1.24190139 -1.65849531 -0.35337169  1.6565077
   1.51191283 -0.90680429 -0.77721733 -0.73922809]]

Matrice dopo la sottrazione della media di ogni riga:
 [[-9.90832514e-01  9.54118627e-01 -2.78119537e-01 -1.14312967e+00
   5.60615366e-01 -2.46944564e+00 -2.19702927e-03  1.07260177e+00
   8.34659591e-01  1.46172903e+00]
 [-1.69259618e-01 -1.26430721e+00  9.49788545e-01  2.18420901e+00
  -1.71356293e-01  1.28045266e+00 -7.08947619e-01 -1.23880993e+00
 